const Images={
    "A": require("./letter/A.jpg"),
    "B": require("./letter/B.jpg"),
    "C": require("./letter/C.jpg"),
    "D": require("./letter/D.jpg"),
    "E": require("./letter/E.jpg"),
    "F": require("./letter/F.jpg"),
    "G": require("./letter/G.jpg"),
    "H": require("./letter/H.jpg"),
    "I": require("./letter/I.jpg"),
    "J": require("./letter/J.jpg"),
    "K": require("./letter/K.jpg"),
    "L": require("./letter/L.jpg"),
    "M": require("./letter/M.jpg"),
    "N": require("./letter/N.jpg"),
    "O": require("./letter/O.jpg"),
    "P": require("./letter/P.jpg"),
    "Q": require("./letter/Q.jpg"),
    "R": require("./letter/R.jpg"),
    "S": require("./letter/S.jpg"),
    "T": require("./letter/T.jpg"),
    "U": require("./letter/U.jpg"),
    "V": require("./letter/V.jpg"),
    "W": require("./letter/W.jpg"),
    "X": require("./letter/X.jpg"),
    "Y": require("./letter/Y.jpg"),
    "Z": require("./letter/Z.jpg"),
    "blank": require("./letter/blank.jpg")
}

export default Images;